import { addDays, subDays } from 'date-fns';

import { Booking, Participant } from '@root/shared';

const today = new Date();

export const bookings: Record<string, Booking> = {
  '1': {
    id: '1',
    projectId: '1',
    type: 'flight',
    startDate: subDays(today, 5).toUTCString(),
    startTime: '11:30',
    endDate: subDays(today, 5).toUTCString(),
    endTime: '13:30',
    provider: 'Austrian airlines',
    participants: ['1', '2', '8'],
    from: 'London - Heathrow',
    to: 'Paris De Gaul',
    image: 'assets/booking-images/flight1.jpg',
  },
  '2': {
    id: '2',
    projectId: '1',
    type: 'hotel',
    startDate: subDays(today, 5).toUTCString(),
    startTime: '14:00',
    endDate: subDays(today, 4).toUTCString(),
    endTime: '12:00',
    provider: 'Sofia grand hotel',
    participants: ['1', '2', '6', '8', '9', '10'],
    city: 'Sofia',
    address: 'Tsar Osvoboditel 13',
    image: 'assets/booking-images/hotel1.jpg',
  },
  '3': {
    id: '3',
    projectId: '2',
    type: 'ferry',
    startDate: subDays(today, 3).toUTCString(),
    startTime: ' 14:00',
    endDate: subDays(today, 3).toUTCString(),
    endTime: '16:00',
    provider: 'Sharky fella',
    participants: ['5', '7'],
    from: 'Istanbul port 1',
    to: 'Istanbul port 2',
    image: 'assets/booking-images/ferry1.jpg',
  },
  '4': {
    id: '4',
    projectId: '3',
    type: 'train',
    startDate: today.toUTCString(),
    startTime: '09:00',
    endDate: today.toUTCString(),
    endTime: '19:00',
    provider: 'Old Tomm',
    participants: ['3', '4', '7'],
    from: 'Moscow',
    to: 'St Petersburg',
    image: 'assets/booking-images/train1.jpg',
  },
  '5': {
    id: '5',
    projectId: '1',
    type: 'flight',
    startDate: today.toUTCString(),
    startTime: '11:30',
    endDate: today.toUTCString(),
    endTime: '13:25',
    provider: 'Qatar airlines',
    participants: ['1', '2', '8', '9', '10'],
    from: 'London - Heathrow',
    to: 'Paris De Gaul',
    image: 'assets/booking-images/flight2.jpg',
  },
  '6': {
    id: '6',
    projectId: '1',
    type: 'flight',
    startDate: addDays(today, 1).toUTCString(),
    startTime: '09:30',
    endDate: addDays(today, 1).toUTCString(),
    endTime: '14:45',
    provider: 'Qatar airlines',
    participants: ['1', '2'],
    from: 'Vienna airport',
    to: 'Qatar',
    image: 'assets/booking-images/flight3.jpg',
  },
  '7': {
    id: '7',
    projectId: '1',
    type: 'train',
    startDate: addDays(today, 1).toUTCString(),
    startTime: '09:30',
    endDate: addDays(today, 2).toUTCString(),
    endTime: '11:00',
    provider: 'Qatar train services',
    participants: ['1', '2', '8', '9', '10'],
    from: 'Qatar central station',
    to: 'Bangalore',
    image: 'assets/booking-images/train1.jpg',
  },
  '8': {
    id: '8',
    projectId: '1',
    type: 'ferry',
    startDate: addDays(today, 3).toUTCString(),
    startTime: '09:30',
    endDate: addDays(today, 3).toUTCString(),
    endTime: '22:00',
    provider: 'Indian ferry services',
    participants: ['1', '2', '3', '4'],
    from: 'Bangalore port',
    to: 'New Zealand',
    image: 'assets/booking-images/ferry2.jpg',
  },
  '9': {
    id: '9',
    projectId: '1',
    type: 'hotel',
    startDate: addDays(today, 5).toUTCString(),
    startTime: '12:00',
    endDate: addDays(today, 7).toUTCString(),
    endTime: '11:00',
    provider: 'K West Hotel and Spa',
    participants: ['1', '2', '3', '4', '8', '9', '10'],
    city: 'London',
    address: 'Richmond Way, London W14 0AX',
    image: 'assets/booking-images/hotel4.jpg',
  },
};

export const participants: Record<string, Participant> = {
  '1': {
    id: '1',
    projectId: '1',
    firstName: 'John',
    lastName: 'Simmons',
    email: 'johns@gmail.com',
    phone: '447969899667',
    passportNumber: '123AB78H',
  },
  '2': {
    id: '2',
    projectId: '1',
    firstName: 'Jean',
    lastName: 'Tennesy',
    email: 'jeant@hotmail.com',
    phone: '441235995998',
    passportNumber: '123AB78H',
  },
  '3': {
    id: '3',
    projectId: '3',
    firstName: 'Eric',
    lastName: 'Gartner',
    email: 'ericg@hotmail.com',
    phone: '441229745677',
    passportNumber: '123AB78H',
  },
  '4': {
    id: '4',
    projectId: '3',
    firstName: 'Vanessa',
    lastName: 'Hughes',
    email: 'vanhughes@gmail.com',
    phone: '447969888777',
    passportNumber: '123AB78H',
  },
  '5': {
    id: '5',
    projectId: '2',
    firstName: 'Patrick',
    lastName: 'Rothfuss',
    email: 'nottodaypat@yahoo.com',
    phone: '447969844776',
    passportNumber: '123AB78H',
  },
  '6': {
    id: '6',
    projectId: '2',
    firstName: 'Patricia',
    lastName: 'Gates',
    email: 'patgates55@yahoo.com',
    phone: '447977158757',
    passportNumber: '123AB78H',
  },
  '7': {
    id: '7',
    projectId: '3',
    firstName: 'Ivan',
    lastName: 'Orlov',
    email: 'luckychicken@gmail.com',
    phone: '447989555444',
    passportNumber: '123AB78H',
  },
  '8': {
    id: '8',
    projectId: '1',
    firstName: 'Charlotte',
    lastName: 'Baby',
    email: 'cbaby@hotmail.com',
    phone: '447475332211',
    passportNumber: '123AB78H',
  },
  '9': {
    id: '9',
    projectId: '1',
    firstName: 'Jake',
    lastName: 'Heart',
    email: 'jakeh@hotmail.com',
    phone: '447798554669',
    passportNumber: '123AB78H',
  },
  '10': {
    id: '10',
    projectId: '1',
    firstName: 'Chloe',
    lastName: 'Fartlec',
    email: 'chloef@hotmail.com',
    phone: '447897457221',
    passportNumber: '123AB78H',
  },
};
